apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-api-ingress
  namespace: dev
spec:
  rules:
  - host: dev.api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-app-service
            port:
              number: 80