apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-api-ingress
  namespace: production
spec:
  rules:
  - host: prod.api.locals
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-app-service
            port:
              number: 80