name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Timestamp for Image Tag
        run: echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_ENV"

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: app/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my_docker_image:${{ env.IMAGE_TAG }}

      - name: Output Image Tag
        run: |
          echo "Built and pushed Docker image with tag: $IMAGE_TAG"
