name: Code Test

on:
  pull_request: #test_pr
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest --cov=app --cov-report=xml
          cp -f coverage.xml ./coverage.xml || true

  sonar:
    runs-on: self-hosted
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Sonar Scanner
        run: |
          mkdir -p $RUNNER_TEMP/sonar-scanner
          curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.2.4839-macosx-x64.zip
          unzip -q sonar-scanner.zip -d $RUNNER_TEMP/sonar-scanner
          echo "$RUNNER_TEMP/sonar-scanner/sonar-scanner-7.0.2.4839-macosx-x64/bin" >> $GITHUB_PATH

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-flask-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"