name: Flask App CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests & Generate Coverage Report
        run: |
          pytest --cov=app --cov-report=xml
      
      - name: Copy Coverage Report (if needed)
        run: |
          if [ -f coverage.xml ] && [ "$PWD" != "$(dirname coverage.xml)" ]; then
            cp coverage.xml ./coverage.xml
          fi


  sonar:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
