name: Test Dockerfile

on:
  pull_request:
    branches:
      - main

jobs:
  docker-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Hadolint
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Run Hadolint on Dockerfile
        run: hadolint Dockerfile


  security-scan:
    runs-on: ubuntu-latest
    needs: docker-lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Trivy for Dependency Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          ignore-unfixed: true
          severity: "MEDIUM,HIGH,CRITICAL"

      - name: Run Trivy for Dockerfile Security
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "Dockerfile"
          ignore-unfixed: true
          severity: "MEDIUM,HIGH,CRITICAL"